name: Deploy to production Environment

on:
  pull_request:
    types: [closed] 
    branches: [main]

jobs:
  build_docker_image:
    if: github.event.pull_request.merged == true
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    outputs:
      image_tag: ${{ steps.meta.outputs.tags }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env file
        env:
          PORT: ${{ secrets.PORT }}
          MONGO_URI: ${{ secrets.MONGO_URI }}
          SERVER_URL: ${{ secrets.SERVER_URL_PROD }}
        run: |
          echo "PORT=${{ env.PORT }}" > .env
          echo "MONGO_URI=${{ env.MONGO_URI }}" >> .env
          echo "SERVER_URL=${{ env.SERVER_URL_PROD }}" >> .env

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker Hub Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME_FERNANDO }}
          password: ${{ secrets.DOCKER_PASSWORD_FERNANDO }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: fernando785/marketplace-mensajeria
          tags: |
            type=raw,value=staging
          
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: fernando785/marketplace-mensajeria:main
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy_to_ec2:
    name: Deploy to EC2 Instances
    runs-on: ubuntu-latest
    needs: build_docker_image
    strategy:
      matrix:
        ec2_instance: 
          - ec2-98-85-141-17.compute-1.amazonaws.com

    steps:
      - name: Configure SSH Key
        run: |
          echo "${{ secrets.EC2_SSH_NEW1 }}" > key.pem
          chmod 600 key.pem
          ls -l key.pem

      - name: Add Host to Known Hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ matrix.ec2_instance }} >> ~/.ssh/known_hosts

      - name: Debug SSH Connection
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ matrix.ec2_instance }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_NEW1 }}
          port: 22
          timeout: "120s"
          script: |
            echo "SSH connection successful"

      - name: Deploy Container
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ matrix.ec2_instance }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_NEW1 }}
          port: 22
          timeout: "120s"
          script: |
            set -e
            echo "Deploying image: fernando785/marketplace-mensajeria:main"
            sudo docker stop messages || true
            sudo docker rm messages || true
            sudo docker pull fernando785/marketplace-mensajeria:main
            sudo docker run -d \
              --name messages \
              -p 4000:4000 \
              --restart unless-stopped \
              fernando785/marketplace-mensajeria:main
            sudo docker system prune -af --volumes || true